### ISSUE TITLE
关于 PoseTracks 数据集

### ISSUE THREAD

**Issue by chenhaomingbob** [bitcodewoker/Paper#4]
https://github.com/bitcodewoker/Paper/blob/master/cv/%E5%A7%BF%E6%80%81%E6%A3%80%E6%B5%8B/PoseTrack17%2618.md

多帧检测下的

PoseWarper是19年NIPS Learning Temporal Pose Estimation from Sparsely-Labeled Videos

CorrTrack是2020 ECCV  Temporal Keypoint Matching and Reﬁnement Network for Pose Estimation and Tracking

建议补上。

**Comment by rm-rf-me** [comment]
非常感谢！已添加。
